### ISSUE TITLE
Check MIME-Type before parsing body content

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/sparql-http-client#37]
Problem:
checkResponse(res) is checking for HTTP Status Code 200 OK. This is not enough. Stardog is answering with Status Code OK on failure but the content is JSON with an Error description. 

In the code ... https://github.com/zazuko/sparql-http-client/blob/b8575ba15260ff3f038326bc757c3bf9f6dff10b/StreamQuery.js#L56

we check ` checkResponse(res)` for HTTP 200 and then the body is parsed with N3Parser. 

```javascript
    await checkResponse(res)

    const parser = new N3Parser({ factory: this.factory })

    return parser.import(res.body)
```

Because Stardog is sending HTTP 200 on error `parser.import(res.body)` tries to parse a JSON body. This leads to a parsing error.
To avoid this we should check if the content type is `application/n-triples` or `text/turtle` before parsing it.

**Comment by tpluscode** [comment]
This should totally be fixed by Stardog too xd

**Comment by mielvds** [comment]
I think I might have this issue as well (also Stardog).
The problem is that I cannot catch this error. I got:
```
SyntaxError: Unexpected token 
 in JSON at position 15
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
    at /app/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by mielvds** [comment]
The error I had turned out unrelated, so I removed the comments.

**Comment by ktk** [comment]
@tpluscode do you have a proposal for what I should report @ Stardog?

**Comment by tpluscode** [comment]
We already have, haven't we?

Regardless of this particular scenario, it is possible that the body is ini whatever way malformed and would fail to parse. Is it so that parser errors are not handled gracefully?
